FROM alpine/git as hanabi-fetch

RUN git clone https://github.com/deepmind/hanabi-learning-environment.git /hanabi-learning-environment

FROM nvidia/cuda:10.2-cudnn7-devel as hanabi-env
COPY --from=hanabi-fetch /hanabi-learning-environment /hanabi_env
RUN apt update && apt install -y --no-install-recommends \
      curl \
      && \
    rm -rf /var/lib/apt/lists/* && \
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3 get-pip.py
RUN cd /hanabi_env && pip install .
