# FROM alpine/git as hanabi-fetch

# RUN git clone https://github.com/deepmind/hanabi-learning-environment.git /hanabi-learning-environment

# FROM python:3.8-buster
# COPY --from=hanabi-fetch /hanabi-learning-environment /hanabi_env
# RUN ls -lah / && cd /hanabi_env && pip install .
FROM hanabi-env:cpu
RUN pip install tensorflow==1.15.2
