#FROM alpine/git as hanabi-fetch
#
#RUN git clone https://github.com/deepmind/hanabi-learning-environment.git /hanabi-learning-environment

FROM hanabi-env:latest
# COPY --from=hanabi-fetch /hanabi-learning-environment /hanabi_env
# RUN ls -lah / && cd /hanabi_env && pip install .
# RUN pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install torch==1.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
