FROM alpine/git as hanabi-fetch

RUN mkdir /dm-tools && \
    git clone https://github.com/deepmind/hanabi-learning-environment.git /dm-tools/hanabi-learning-environment && \
    git clone https://github.com/deepmind/dm_env /dm-tools/dm-env && \
    git clone https://github.com/deepmind/dm-haiku /dm-tools/dm-haiku && \
    git clone https://github.com/deepmind/rlax.git /dm-tools/rlax && \
    wget -O /dm-tools/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

FROM nvidia/cuda:10.1-cudnn7-devel
COPY --from=hanabi-fetch /dm-tools /dm-tools/

# conda
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

RUN /bin/bash /dm-tools/miniconda.sh -b -p /opt/conda && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    find /opt/conda/ -follow -type f -name '*.a' -delete && \
    find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
    /opt/conda/bin/conda clean -afy && \
    pip install --upgrade pip

RUN cd /dm-tools && ls -lah && \
    cd hanabi-learning-environment && pip install . && cd .. && \
    cd dm-env                      && pip install . && cd .. && \
    cd dm-haiku                    && pip install . && cd .. && \
    cd rlax                        && pip install . && cd ..

ADD install_jax.sh /
RUN sh /install_jax.sh && \
    rm -rf /dm-tools

CMD [ "/bin/bash" ]
